/* Generated By:JJTree: Do not edit this line. ASTinput.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.ingenta.search.parse;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.ingenta.search.domain.*;

public class ASTinput extends SimpleNode {
   private static final Logger LOG = Logger.getLogger(ASTinput.class);
  public ASTinput(int id) {
    super(id);
  }

  public ASTinput(SearchExpressionParser p, int id) {
    super(p, id);
  }

  public void interpret() {

        for (int i = 0; i < jjtGetNumChildren(); i++){

        	Node[] nodes = children;
        	for (int j = 0; j < children.length; j++){
				LOG.debug( "token is :[" + j + "]:" + ((SimpleNode)children[j]).toString() );
			}

            jjtGetChild(i).interpret();
		}

  }

  public List<SearchTerm> getSearchTermList(){

  	List<SearchTerm> searchTermList = new ArrayList<SearchTerm>();

  	for (int i = 0; i < jjtGetNumChildren(); i++){

  		Node[] nodes = children;

  		if( ((SimpleNode)nodes[i]).id == SearchExpressionParserTreeConstants.JJTSTRINGORPHRASEORGROUP ){
  			searchTermList.addAll(((SimpleNode)jjtGetChild(i)).getSearchTermList());
  		}
  		else{
  			searchTermList.add(((SimpleNode)jjtGetChild(i)).getSearchTerm());
  		}
  	}

  	return searchTermList;

  }

}
/* JavaCC - OriginalChecksum=64ddf321df606bae0b60fa9df924613a (do not edit this line) */
