/* Generated By:JJTree: Do not edit this line. ASToperator.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.ingenta.search.parse;

import org.apache.log4j.Logger;

import com.ingenta.search.domain.*;

public class ASToperator extends SimpleNode {
   private static final Logger LOG = Logger.getLogger(ASToperator.class);
   
  public ASToperator(int id) {
    super(id);
  }

  public ASToperator(SearchExpressionParser p, int id) {
    super(p, id);
  }

  public void interpret() {
	  LOG.debug( "token is : " + val );
  }

  public SearchTerm getSearchTerm(){
	  return new OperatorTerm(Operator.valueOf(val));
  }


}
/* JavaCC - OriginalChecksum=24fd8f3806b34cb7bf3c5812be418886 (do not edit this line) */
