/* Generated By:JJTree: Do not edit this line. ASTstringorphrase.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY= */
package com.ingenta.search.parse;
import org.apache.log4j.Logger;

import com.ingenta.search.domain.*;

public class ASTstringorphrase extends SimpleNode {
   private static final Logger LOG = Logger.getLogger(ASTstringorphrase.class);
   
  public ASTstringorphrase(int id) {
    super(id);
  }

  public ASTstringorphrase(SearchExpressionParser p, int id) {
    super(p, id);
  }

  public void interpret() {
	  LOG.debug( "token is : " + val );
  }

  public SearchTerm getSearchTerm(){

	  //if (getFirstToken().kind == SearchExpressionParserConstants.STRING){
	  if (! (val.startsWith("\"") || val.startsWith("'"))){
	  
		  return new ValueTerm(val);
	  }
	  else{ // it is a phrase
		  return new ValuePhraseTerm(val.replaceAll("^'", "\"").replaceAll("'$", "\""));
	  }

  }


}
/* JavaCC - OriginalChecksum=e3a7a65e71a6ac23beca464ed98f9326 (do not edit this line) */
