/* Generated By:JavaCC: Do not edit this line. SearchExpressionParserTreeConstants.java Version 4.1 */
package com.ingenta.search.parse;

public interface SearchExpressionParserTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTGROUP = 1;
  public int JJTSTRINGORPHRASEORGROUP = 2;
  public int JJTSTRINGORPHRASE = 3;
  public int JJTOPERATOR = 4;


  public String[] jjtNodeName = {
    "input",
    "group",
    "stringorphraseorgroup",
    "stringorphrase",
    "operator",
  };
}
/* JavaCC - OriginalChecksum=b666816fedf813f5eb20f233f2761638 (do not edit this line) */
