/* Generated By:JJTree&JavaCC: Do not edit this line. SearchExpressionParserConstants.java */
package com.ingenta.search.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SearchExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EF = 2;
  /** RegularExpression Id. */
  int OR = 3;
  /** RegularExpression Id. */
  int AND = 4;
  /** RegularExpression Id. */
  int NOT = 5;
  /** RegularExpression Id. */
  int LPAR = 6;
  /** RegularExpression Id. */
  int RPAR = 7;
  /** RegularExpression Id. */
  int STRING = 8;
  /** RegularExpression Id. */
  int PHRASE1 = 9;
  /** RegularExpression Id. */
  int PHRASE2 = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EF>",
    "\"OR\"",
    "<AND>",
    "<NOT>",
    "\"(\"",
    "\")\"",
    "<STRING>",
    "<PHRASE1>",
    "<PHRASE2>",
  };

}
